version: 2
updates:
- package-ecosystem: gomod
  directory: "/backend"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
