version: 2
updates:
- package-ecosystem: gomod
  directory: "/backend"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/labstack/echo/v4
    versions:
    - 4.2.0
  - dependency-name: github.com/slack-go/slack
    versions:
    - 0.8.0
  - dependency-name: github.com/google/go-cmp
    versions:
    - 0.5.4
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@material-ui/lab"
    versions:
    - 4.0.0-alpha.57
  - dependency-name: next
    versions:
    - 10.0.5
    - 10.0.6
    - 10.0.7
    - 10.0.8
    - 10.0.9
    - 10.1.1
    - 10.1.2
    - 10.1.3
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.27
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: type-fest
    versions:
    - 0.20.2
    - 0.21.0
    - 0.21.1
    - 0.21.2
    - 0.21.3
    - 1.0.0
    - 1.0.1
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: ky
    versions:
    - 0.26.0
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: "@reduxjs/toolkit"
    versions:
    - 1.5.0
