version: "3"

services:
  envoy:
    image: envoyproxy/envoy:latest
    entrypoint: "/usr/local/bin/envoy"
    command:
      - "--config-path /etc/envoy/envoy.yaml"
      - "--base-id 1"
    ports:
      - 10080:80
    volumes:
      - ./envoy:/etc/envoy

  app:
    build:
      dockerfile: dev.Dockerfile
      context: .
    env_file: ./dev.env
    volumes:
      - ./frontend:/frontend
    expose:
      - "80"
      - "3000"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portal
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql:
