version: "3"

services:
  envoy:
    image: envoyproxy/envoy:latest
    entrypoint: "/usr/local/bin/envoy"
    command:
      - "--config-path /etc/envoy/envoy.yaml"
      - "--base-id 1"
    ports:
      - 10080:80
    volumes:
      - ./envoy:/etc/envoy

  backend:
    build:
      dockerfile: backend.Dockerfile
      context: .
    env_file: ./dev.env
    volumes:
      - ./backend:/backend
      - ./backend/schema:/schema
      - ./scripts/docker-entrypoint.backend.sh:/bin/docker-entrypoint.backend.sh
    expose:
      - "80"
    environment:
      TZ: "Azia/Tokyo"
      ENVIRONMENT: dev

  frontend:
    build:
      dockerfile: frontend.Dockerfile
      context: .
    env_file: ./dev.env
    volumes:
      - ./frontend:/frontend
      - ./scripts/docker-entrypoint.frontend.sh:/bin/docker-entrypoint.frontend.sh
    expose:
      - "3000"
    environment:
      TZ: "Azia/Tokyo"
      ENVIRONMENT: dev

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portal
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql:
