// Code generated by MockGen. DO NOT EDIT.
// Source: internal/middleware/role.go

// Package middleware is a generated GoMock package.
package middleware

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	echo "github.com/labstack/echo/v4"
)

// MockRoleValidationMiddleware is a mock of RoleValidationMiddleware interface.
type MockRoleValidationMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockRoleValidationMiddlewareMockRecorder
}

// MockRoleValidationMiddlewareMockRecorder is the mock recorder for MockRoleValidationMiddleware.
type MockRoleValidationMiddlewareMockRecorder struct {
	mock *MockRoleValidationMiddleware
}

// NewMockRoleValidationMiddleware creates a new mock instance.
func NewMockRoleValidationMiddleware(ctrl *gomock.Controller) *MockRoleValidationMiddleware {
	mock := &MockRoleValidationMiddleware{ctrl: ctrl}
	mock.recorder = &MockRoleValidationMiddlewareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleValidationMiddleware) EXPECT() *MockRoleValidationMiddlewareMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockRoleValidationMiddleware) Authenticate(next echo.HandlerFunc) echo.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", next)
	ret0, _ := ret[0].(echo.HandlerFunc)
	return ret0
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockRoleValidationMiddlewareMockRecorder) Authenticate(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockRoleValidationMiddleware)(nil).Authenticate), next)
}
