// Code generated by MockGen. DO NOT EDIT.
// Source: slack_repository.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	domain "github.com/MISW/Portal/backend/domain"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockSlackRepository is a mock of SlackRepository interface
type MockSlackRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSlackRepositoryMockRecorder
}

// MockSlackRepositoryMockRecorder is the mock recorder for MockSlackRepository
type MockSlackRepositoryMockRecorder struct {
	mock *MockSlackRepository
}

// NewMockSlackRepository creates a new mock instance
func NewMockSlackRepository(ctrl *gomock.Controller) *MockSlackRepository {
	mock := &MockSlackRepository{ctrl: ctrl}
	mock.recorder = &MockSlackRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSlackRepository) EXPECT() *MockSlackRepositoryMockRecorder {
	return m.recorder
}

// UpdateSlackID mocks base method
func (m *MockSlackRepository) UpdateSlackID(ctx context.Context, id int, slackID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSlackID", ctx, id, slackID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSlackID indicates an expected call of UpdateSlackID
func (mr *MockSlackRepositoryMockRecorder) UpdateSlackID(ctx, id, slackID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSlackID", reflect.TypeOf((*MockSlackRepository)(nil).UpdateSlackID), ctx, id, slackID)
}

// MarkUninvitedAsPending mocks base method
func (m *MockSlackRepository) MarkUninvitedAsPending(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkUninvitedAsPending", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkUninvitedAsPending indicates an expected call of MarkUninvitedAsPending
func (mr *MockSlackRepositoryMockRecorder) MarkUninvitedAsPending(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkUninvitedAsPending", reflect.TypeOf((*MockSlackRepository)(nil).MarkUninvitedAsPending), ctx)
}

// GetPending mocks base method
func (m *MockSlackRepository) GetPending(ctx context.Context) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPending", ctx)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPending indicates an expected call of GetPending
func (mr *MockSlackRepositoryMockRecorder) GetPending(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPending", reflect.TypeOf((*MockSlackRepository)(nil).GetPending), ctx)
}

// MarkAsInvited mocks base method
func (m *MockSlackRepository) MarkAsInvited(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsInvited", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsInvited indicates an expected call of MarkAsInvited
func (mr *MockSlackRepositoryMockRecorder) MarkAsInvited(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsInvited", reflect.TypeOf((*MockSlackRepository)(nil).MarkAsInvited), ctx, id)
}
