CREATE TABLE appconfig (
    key VARCHAR(255) NOT NULL PRIMARY KEY,
    value LONGTEXT,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);