CREATE TABLE appconfig (
    configkey VARCHAR(255) NOT NULL PRIMARY KEY,
    configvalue LONGTEXT,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
