// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/externalIntegration.go

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockExternalIntegrationUsecase is a mock of ExternalIntegrationUsecase interface.
type MockExternalIntegrationUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockExternalIntegrationUsecaseMockRecorder
}

// MockExternalIntegrationUsecaseMockRecorder is the mock recorder for MockExternalIntegrationUsecase.
type MockExternalIntegrationUsecaseMockRecorder struct {
	mock *MockExternalIntegrationUsecase
}

// NewMockExternalIntegrationUsecase creates a new mock instance.
func NewMockExternalIntegrationUsecase(ctrl *gomock.Controller) *MockExternalIntegrationUsecase {
	mock := &MockExternalIntegrationUsecase{ctrl: ctrl}
	mock.recorder = &MockExternalIntegrationUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExternalIntegrationUsecase) EXPECT() *MockExternalIntegrationUsecaseMockRecorder {
	return m.recorder
}

// GetAllMemberRolesByAccountID mocks base method.
func (m *MockExternalIntegrationUsecase) GetAllMemberRolesByAccountID(ctx context.Context) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMemberRolesByAccountID", ctx)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMemberRolesByAccountID indicates an expected call of GetAllMemberRolesByAccountID.
func (mr *MockExternalIntegrationUsecaseMockRecorder) GetAllMemberRolesByAccountID(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMemberRolesByAccountID", reflect.TypeOf((*MockExternalIntegrationUsecase)(nil).GetAllMemberRolesByAccountID), ctx)
}

// GetUserRoleFromAccountID mocks base method.
func (m *MockExternalIntegrationUsecase) GetUserRoleFromAccountID(accountID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRoleFromAccountID", accountID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRoleFromAccountID indicates an expected call of GetUserRoleFromAccountID.
func (mr *MockExternalIntegrationUsecaseMockRecorder) GetUserRoleFromAccountID(accountID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRoleFromAccountID", reflect.TypeOf((*MockExternalIntegrationUsecase)(nil).GetUserRoleFromAccountID), accountID)
}
