name: Add stats comment

on:
  workflow_run:
    workflows:
      - frontend
    types:
      - completed

jobs:
  add-stats-comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Echo event
        run: echo ${{ toJSON(github.event) }}
