name: Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image for Frontend
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: portal/frontend
          registry: registry.misw.jp
          dockerfile: frontend.Dockerfile
          tag_with_ref: true
          tag_with_sha: true

      - name: Build Docker Image for API Server
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: portal/backend
          registry: registry.misw.jp
          dockerfile: backend.Dockerfile
          tag_with_ref: true
          tag_with_sha: true
