name: Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login --password-stdin -u misw docker.pkg.github.com

      - if: github.actor != 'dependabot-preview[bot]'
        name: Docker build
        run: |
          docker build . -t docker.pkg.github.com/misw/portal/portal-server:${{ github.sha }}
          docker push docker.pkg.github.com/misw/portal/portal-server:${{ github.sha }}
