name: Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login --password-stdin -u misw docker.pkg.github.com

      - name: Build Docker Image for Frontend
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: registry.misw.jp/MISW/Portal/frontend
          dockerfile: frontend.Dockerfile
          tag_with_ref: true
          tag_with_sha: true

      - name: Build Docker Image for API Server
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: registry.misw.jp/MISW/Portal/backend
          dockerfile: backend.Dockerfile
          tag_with_ref: true
          tag_with_sha: true
