# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  pull_request:

defaults:
  run:
    working-directory: frontend

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      # FIXME: https://github.com/actions/setup-node/issues/282 が解決されたら actions/setup-node のキャッシュを使う
      - name: Install npm packages
        uses: bahmutov/npm-install@v1
        with:
          working-directory: frontend
      - name: ESLint
        run: npm run lint -- --quiet
      - name: Typecheck
        run: npm run typecheck
